### ISSUE TITLE
urequests.post的问题

### ISSUE THREAD

**Issue by haozi-dev** [labplus-cn/mpython#19]
1.首先，使用的协议是老旧的http1.0，至少也该http1.1吧。
2.远端api服务器一切正常，本地用浏览器post毫无问题，用urequests.post服务器就返回408错误。

**Comment by haozidev** [comment]
还有audio的引脚找不到

**Comment by lgnativs** [comment]
> 还有audio的引脚找不到
使用P8/P9引脚分别输出左右声道.

**Comment by haozidev** [comment]
> > 还有audio的引脚找不到
> 
> 使用P8/P9引脚分别输出左右声道.

掌控板上面没得，是在哪个模块上面吗

**Comment by haozidev** [comment]
还有，不支持https，get方法请求附加的参数没有附加到url上面，post的参数完全取不到

**Comment by zjuxumang** [comment]
urequests.post上传文件，文件能成功上传，但是程序会卡住，等一段时间后报如下错误
```
Traceback (most recent call last):                                                                                                                                                                                                 
  File "main.py", line 18, in <module>                                                                                                                                                                                             
  File "urequests.py", line 147, in post                                                                                                                                                                                           
  File "urequests.py", line 120, in request                                                                                                                                                                                        
ValueError: need more than 0 values to unpack 
```

调用方法如下
```
files = {'image':('capture.jpg','multipart/form-data')}
_response = urequests.post(url,files=files)
```

**Comment by zjuxumang** [comment]
> urequests.post上传文件，文件能成功上传，但是程序会卡住，等一段时间后报如下错误
> 
> ```
> Traceback (most recent call last):                                                                                                                                                                                                 
>   File "main.py", line 18, in <module>                                                                                                                                                                                             
>   File "urequests.py", line 147, in post                                                                                                                                                                                           
>   File "urequests.py", line 120, in request                                                                                                                                                                                        
> ValueError: need more than 0 values to unpack 
> ```
> 
> 调用方法如下
> 
> ```
> files = {'image':('capture.jpg','multipart/form-data')}
> _response = urequests.post(url,files=files)
> ```

使用仓库里最新的urequests.py替换了固件自带的，测试成功了，等发布新固件吧

**Comment by haozi-dev** [comment]
ok
